//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFirst1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> PhongBan_Id { get; set; }
        public Nullable<int> Gender { get; set; }
    
        public virtual PhongBan PhongBan { get; set; }
    }
}
